version: 1.0.0.{build}
image: Visual Studio 2015
configuration:
- Release
- Debug
- Steam
platform: Any CPU
shallow_clone: true
environment:
  APIKeys:
    secure: oWmEefxkbok87VNVsrUuXKgNaM4+j+EW6FBLsXwCbv3OVHgFvT0M9k4891OvYXDsj0oLuEn0oZeaeV8RrRDHA2Hk2acXHrWkg9z6FCGASxRMJjv0+in1v5DxN1BfEPdASmhnYFu6pcINmwibGYjsxySek57cbYUDc69yQfyqX6FUI0kQcEGp8Dh3tHF981Dy
install:
- ps: AppVeyor\install.ps1
before_build:
- ps: AppVeyor\before_build.ps1
build:
  project: ShareX.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: AppVeyor\after_build.ps1
artifacts:
- path: ShareX.Setup\InnoSetup\Output\ShareX-*-setup.exe
  name: Setup
- path: ShareX.Setup\InnoSetup\Output\ShareX-portable.zip
  name: Portable
- path: ShareX.Setup\InnoSetup\Output\ShareX-Steam
  name: Steam
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: ShareX $(AppVersion)
  description: "[Changelog](https://github.com/ShareX/ShareX/wiki/Changelog)"
  auth_token:
    secure: bbUkNvyu1jnKkuZGlM1ois3MkmpCMlm3Lv68L9V5AYepHt1SG4ZQ15ZoKfjOFg9R
  artifact: Setup,Portable
  draft: true
  prerelease: true
  on:
    configuration: Release
    appveyor_repo_tag: true